### PR TITLE
Build and push app and migrations dockerfiles to AWS ECR

### PR DESCRIPTION
**Pull request by chrisgilmerproj**
## Description

This sets up build and push for the dockerfiles against AWS ECR.

New in this PR: Using CircleCI Orbs to manage ECR and Slack notifications.

You should check out the ECR repo and see images:

https://us-west-2.console.aws.amazon.com/ecr/repositories/orders/?region=us-west-2

Also check out the CircleCI build pipeline: 

https://circleci.com/workflow-run/41b17d3b-8b65-48ed-b366-d01faced71b4

## Setup

You may want to test that these images do what they are supposed to do, so here's how. Use docker-compose to test the images built and pushed to AWS:

```sh
make docker_compose_branch_up
```

When finished run:

```sh
make docker_compose_branch_down
```

### CODE REVIEW

**Review by mr337 — CHANGES_REQUESTED** [review]
Everything looking good except standing up the docker compose.
```sh
 $ make docker_compose_branch_up
aws-vault exec "transcom-ppp" -- aws ecr get-login-password --region "us-west-2" | docker login --username AWS --password-stdin ".dkr.ecr.us-west-2.amazonaws.com"
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument operation: Invalid choice, valid choices are:

batch-check-layer-availability           | batch-delete-image
batch-get-image                          | complete-layer-upload
create-repository                        | delete-lifecycle-policy
delete-repository                        | delete-repository-policy
describe-image-scan-findings             | describe-images
describe-repositories                    | get-authorization-token
get-download-url-for-layer               | get-lifecycle-policy
get-lifecycle-policy-preview             | get-repository-policy
initiate-layer-upload                    | list-images
list-tags-for-resource                   | put-image
put-image-scanning-configuration         | put-image-tag-mutability
put-lifecycle-policy                     | set-repository-policy
start-image-scan                         | start-lifecycle-policy-preview
tag-resource                             | untag-resource
upload-layer-part                        | get-login
help
Error: Cannot perform an interactive login from a non TTY device
Makefile:257: recipe for target 'docker_compose_branch_up' failed
make: *** [docker_compose_branch_up] Error 1
```

I think this repo uses the newer awscli but prereq script not saying anything is off. Ignore the opsec warnings.

```
$ ./scripts/prereqs
aws installed.
bash installed.
chamber installed.
docker installed.
jq installed.
go installed.
pre-commit installed.
shellcheck installed.
psql installed.
WARNING: pkcs11-tool not found, install via: brew install opensc; chmod go+w /usr/local/bin/pkcs11-tool; brew link opensc
WARNING: pkcs15-tool not found, install via: brew install opensc; chmod go+w /usr/local/bin/pkcs15-tool; brew link opensc
circleci installed.
direnv installed.
entr installed.
aws-vault installed.
ERROR: some prereqs missing, please install them.
```

**Comment by mr337** [comment]
Forgot to add I am running version
```
 $ aws --version
aws-cli/1.16.274 Python/2.7.15+ Linux/4.15.0-88-generic botocore/1.13.10
```

**Comment by chrisgilmerproj** [comment]
@mr337 - You've got to upgrade! Time to start using awscli v2:) They changed the ECR login to docker in v2 so that you have to pass the password into the docker command with a pipe. Previously it did it for you. Also the new command doesn't exist in v1.

**Review by mr337 — APPROVED** [review]
All the infra related parts look to be working and the container issues we can troubleshoot down the road if needed and once I get my rig properly updated.

I may put together a snippet in the prereq to properly check the aws version.

🚢

**Comment by chrisgilmerproj** [comment]
> I may put together a snippet in the prereq to properly check the aws version.

I'm torn on this, especially since I may want to only have AWS CLI installed in the docker container. It's possible what we need here is more like:

```
aws-vault exec "${AWS_PROFILE}" -- docker run -it milmove/milmove-orders aws ecr get-login-password --region "${AWS_DEFAULT_REGION}" | docker login --username AWS --password-stdin "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
```

In the example above all you need is `aws-vault` because `aws` is in the container and is the version we expect for the project.

**Comment by mr337** [comment]
The new docker command works but I need to hash out my envrc

```
 Get https://.dkr.ecr.us-west-2.amazonaws.com/v2/: dial tcp: lookup .dkr.ecr.us-west-2.amazonaws.com: no such host
```

This pr is g2g 🚢

**Comment by chrisgilmerproj** [comment]
> The new docker command works but I need to hash out my envrc

My guess is just do this:

```sh
cp .envrc.chamber.template .envrc.chamber
direnv allow
```

**Pull request merged**
